### ISSUE TITLE
Meta&Tefri

### ISSUE THREAD

**Issue by MrShiposha** [Owldream/Ginseng#13]
# Meta and TeFRI

## Implement Template Function Reactive Interface (TeFRI)
  * [ ] Compile-time check of types (besides operators that can't know about types, e.g. `take_last` on first place in operator pipeline)
  * [ ] Implement `OperatorPipeline`
  * [ ] Implement `Source`, `Flow`, `Jet`
  * [ ] Come up with value-Operator's creation rules
  * [ ] Come up with flow-Operator's creation rules
  * [ ] Type index map for subscribers and error handlers
  -- TODO --
## Refactor Meta 
  * [ ] Rename `FunctionTrait` to `Function` and rename nested types `ReturnType` to `Result`, `ArgumentTypes` to `ArgumentsTuple`, add `Argument<N>` and rename constant `argument_count` to `ARGUMENT_COUNT`
  * [ ] Add `Tuple` class with constexpr `operator+` for concat and constexpr `size` function
  
## Implement Tests
  * Use Google Test
 -- TODO --
