### ISSUE TITLE
class meta::Tuple

### ISSUE THREAD

**Issue by MrShiposha** [Owldream/Ginseng#18]
# `Tuple`
## Methods and operators (include `std::tuple`)
# Write Tests for `Tuple`
  * [x] `operator+`, `concat
  * [x] `size`, `get_size`
  * [x] `for_each`, `for_each_types`
  * [ ] `filter`, `filter_types`
  * [ ] `map`, `map_types`
  * [ ] `every`, `every_types`
  * [ ] `take_first`, `take_first_types` 
  * [ ] `take_last`, `take_last_types`
  * [ ] `take_while`, `take_while_types`
  * [x] `skip_first`, `skip_first_types`
  * [ ] `skip_last`, `skip_last_types`
  * [ ] `skip_while`, `skip_while_types`
  * [ ] `find`, `find_types`
  * [ ] `reduce`
  * [ ] `sum`
  * [ ] `average`
  * [ ] `combine_latest`, `combine_latest_types`
  * [ ] `with_latest_from`, `with_latest_from_types`
  * [ ] `zip`, `zip_types`
  * [ ] `distinct`, `distinct_types`
  * [ ] `distinct_until_changed`, `distinct_until_changed_types`
  * [ ] `find_index`, `find_index_types`
  * [ ] `first`, `first_types`
  * [ ] `last`, `last_types`
  * [ ] `max`
  * [ ] `min`
  * [ ] `map_to`
  * [ ] `pairwise`, `pairwise_types`
  * [ ] `repeat`, `repeat_types`
  * [ ] `scan`
